# Generated by Django 3.2.5 on 2021-07-10 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('identitycard', models.IntegerField()),
                ('age', models.IntegerField()),
                ('bmi', models.FloatField()),
                ('glucouse', models.FloatField()),
                ('insuline', models.FloatField()),
                ('homa', models.FloatField()),
                ('leptin', models.FloatField()),
                ('adiponcetin', models.FloatField()),
                ('resistiin', models.FloatField()),
                ('mcp', models.FloatField()),
                ('classification', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
